### ISSUE TITLE
Question about Janossy gru

### ISSUE THREAD

**Issue by dongZheX** [davidbuterez/gnn-neural-readouts#1]
Hello, I have a question about janossy gru.
In the paper, it is described that the input of gru is (M,D), output is (M,d_out).

In the [code](https://github.com/davidbuterez/gnn-neural-readouts/blob/main/code/models/janossy_pooling.py), the input of GPU  seems to (D, M), output is (D, d_out).

Is this correct ? 
 

Thanks.

**Comment by davidbuterez** [comment]
Thanks for pointing this out! This seems to be an error most likely caused by following the format of the [official GRU documentation](https://pytorch.org/docs/stable/generated/torch.nn.GRU.html) and disregarding the fact that the inputs are permuted before applying the GRU module (e.g. `x.permute(0, 2, 1)`).

The shape of tensors right before the GRU should be `[batch_size, gnn_output_node_dim, max_num_nodes_in_graph]` and the shape of the final graph embeddings should be `[batch_size, gnn_output_node_dim]`.
